GET http://localhost:3001/login?email=d@qqq.n&password=1234

###

POST http://localhost:3001/signup
Content-Type: application/json

{
    "email": "3@gmail.com",
    "pass": "Riponbiswas1@",
    "cpass": "Riponbiswas1@"
}

###

POST http://localhost:3001/post
Content-Type: application/json

{
    "email": "ripon",
    "content": "chakri ta ami peye gechi bela suncho????"
}

###

GET http://localhost:3001/

###

GET http://localhost:3001/my-post
Content-Type: application/json

{
    "email": "riponbiswas"
}

###

POST http://localhost:3001/group
Content-Type: application/json

{
    "name": "diganta",
    "user":"djak",
    "bio":"this is my grp bio"
}

###

GET http://localhost:3001/group

###

POST http://localhost:3001/grp-post-comment
Content-Type: application/json

{
    "content":"comments running3"
}

###

POST http://localhost:3001/grp-post
Content-Type: application/json

{
    "admin":"diganta",
    "content":"post1"
}

###

GET http://localhost:3001/group?id=64510d6e23e9da804ea3bf91
